# Generated by Django 5.1.3 on 2025-01-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Référence de l'année scolaire",
                    ),
                ),
                ("debut", models.DateField(verbose_name="Date de début")),
                ("fin", models.DateField(verbose_name="Date de fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[("En cours", "En cours"), ("Clôturée", "Clôturée")],
                        default="En cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "nombre_classes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de classes"
                    ),
                ),
                (
                    "nombre_eleves",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'élèves"
                    ),
                ),
                (
                    "nombre_professeurs",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de professeurs"
                    ),
                ),
                (
                    "nombre_examens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre d'examens"
                    ),
                ),
                (
                    "nombre_surveillants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de surveillants"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-debut"],
            },
        ),
    ]
