# Generated by Django 5.1.3 on 2025-01-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Professeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("Homme", "Homme"), ("Femme", "Femme")],
                        max_length=10,
                        verbose_name="Sexe",
                    ),
                ),
                (
                    "specialite",
                    models.CharField(max_length=100, verbose_name="Spécialité"),
                ),
                ("date_embauche", models.DateField(verbose_name="Date d'embauche")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professeurs",
                        to="application.anneescolaire",
                        verbose_name="Année Scolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Professeur",
                "verbose_name_plural": "Professeurs",
                "ordering": ["nom", "prenom"],
            },
        ),
    ]
