# Generated by Django 5.1.3 on 2025-01-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_professeur"),
    ]

    operations = [
        migrations.AddField(
            model_name="professeur",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="professeurs/",
                verbose_name="Photo du Professeur",
            ),
        ),
    ]
