# Generated by Django 5.1.3 on 2025-01-31 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_professeur_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Référence de la matière",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la matière"
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveIntegerField(default=1, verbose_name="Coefficient"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Semestre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence du semestre"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("Semestre 1", "Semestre 1"),
                            ("Semestre 2", "Semestre 2"),
                        ],
                        max_length=20,
                        verbose_name="Nom du semestre",
                    ),
                ),
                ("debut", models.DateField(verbose_name="Date de début du semestre")),
                ("fin", models.DateField(verbose_name="Date de fin du semestre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semestres",
                        to="application.anneescolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semestre",
                "verbose_name_plural": "Semestres",
                "ordering": ["-debut"],
                "unique_together": {("nom", "annee_scolaire")},
            },
        ),
    ]
