# Generated by Django 5.1.3 on 2025-01-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_matiere_semestre"),
    ]

    operations = [
        migrations.AddField(
            model_name="matiere",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Matirere/",
                verbose_name="Photo de de la Matiere",
            ),
        ),
    ]
