# Generated by Django 5.1.3 on 2025-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_matiere_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matiere",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Matieres/",
                verbose_name="Photo de la Matière",
            ),
        ),
        migrations.AlterField(
            model_name="matiere",
            name="reference",
            field=models.CharField(
                blank=True,
                max_length=50,
                unique=True,
                verbose_name="Référence de la matière",
            ),
        ),
    ]
