# Generated by Django 5.1.3 on 2025-02-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_alter_matiere_image_alter_matiere_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du Niveau"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Ordre d'affichage"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["ordre"],
            },
        ),
    ]
