# Generated by Django 5.1.3 on 2025-02-03 11:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0010_classe_type_salle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classe",
            name="type_salle",
        ),
    ]
