# Generated by Django 5.1.3 on 2025-02-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0011_remove_classe_type_salle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salle",
            name="type_salle",
            field=models.CharField(
                choices=[
                    ("Salle de classe", "Salle de classe"),
                    ("Laboratoire", "Laboratoire"),
                    ("Salle informatique", "Salle informatique"),
                    ("Bibliothèque", "Bibliothèque"),
                    ("Salle des professeurs", "Salle des professeurs"),
                    ("Salle de réunion", "Salle de réunion"),
                    ("Amphithéâtre", "Amphithéâtre"),
                    ("Autre", "Autre"),
                ],
                default="Salle de classe",
                max_length=30,
                verbose_name="Type de salle",
            ),
        ),
    ]
