# Generated by Django 5.1.3 on 2025-02-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0012_alter_salle_type_salle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salle",
            name="reference",
            field=models.CharField(
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Référence de la salle",
            ),
        ),
    ]
