# Generated by Django 5.1.3 on 2025-02-03 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0013_alter_salle_reference"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Classe",
        ),
        migrations.DeleteModel(
            name="Salle",
        ),
    ]
