# Generated by Django 5.1.3 on 2025-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0015_salle_classe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salle",
            name="reference",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Référence de la salle"
            ),
        ),
    ]
