# Generated by Django 5.1.3 on 2025-02-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0017_eleve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eleve",
            name="nationalite",
        ),
        migrations.AddField(
            model_name="eleve",
            name="annee_scolaire",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Eleve",
                to="application.anneescolaire",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eleve",
            name="classe",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Eleve",
                to="application.classe",
            ),
            preserve_default=False,
        ),
    ]
