# Generated by Django 5.1.3 on 2025-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0018_remove_eleve_nationalite_eleve_annee_scolaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="frais_inscription",
            field=models.CharField(
                choices=[("P", "Payée")],
                max_length=20,
                verbose_name="Frais_inscription",
            ),
        ),
        migrations.AlterField(
            model_name="eleve",
            name="matricule",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Matricule"
            ),
        ),
    ]
