# Generated by Django 5.1.3 on 2025-02-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0019_alter_eleve_frais_inscription_alter_eleve_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="matricule",
            field=models.CharField(blank=True, max_length=20, verbose_name="Matricule"),
        ),
    ]
