# Generated by Django 5.1.3 on 2025-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0020_alter_eleve_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="matricule",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Matricule"
            ),
        ),
    ]
