# Generated by Django 5.1.3 on 2025-02-04 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0022_alter_eleve_matricule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eleve",
            options={},
        ),
    ]
