# Generated by Django 5.1.3 on 2025-02-08 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0025_alter_matiere_coefficient"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notedevoir",
            unique_together={("devoir", "eleve")},
        ),
    ]
