# Generated by Django 5.1.3 on 2025-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0026_alter_notedevoir_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notedevoir",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="notedevoir",
            constraint=models.UniqueConstraint(
                fields=("devoir", "eleve"), name="unique_devoir_eleve"
            ),
        ),
    ]
