# Generated by Django 5.1.3 on 2025-02-08 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0027_alter_notedevoir_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notedevoir",
            name="unique_devoir_eleve",
        ),
    ]
