# Generated by Django 5.1.3 on 2025-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0028_remove_notedevoir_unique_devoir_eleve"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notedevoir",
            constraint=models.UniqueConstraint(
                fields=("devoir", "eleve"), name="unique_devoir_eleve"
            ),
        ),
    ]
