# Generated by Django 5.1.3 on 2025-02-11 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0029_notedevoir_unique_devoir_eleve"),
    ]

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de l'absence")),
                (
                    "duree",
                    models.PositiveIntegerField(verbose_name="Durée (en heures)"),
                ),
                (
                    "justifiee",
                    models.BooleanField(
                        default=False, verbose_name="Absence justifiée"
                    ),
                ),
                (
                    "motif",
                    models.TextField(blank=True, null=True, verbose_name="Motif"),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="application.anneescolaire",
                        verbose_name="Année Scolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="application.classe",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="application.eleve",
                        verbose_name="Élève",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="application.matiere",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="application.semestre",
                        verbose_name="Semestre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence",
                "verbose_name_plural": "Absences",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Retard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date du retard")),
                ("heure_arrivee", models.TimeField(verbose_name="Heure d'arrivée")),
                (
                    "justifie",
                    models.BooleanField(default=False, verbose_name="Retard justifié"),
                ),
                (
                    "raison",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raison du retard"
                    ),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retards",
                        to="application.anneescolaire",
                        verbose_name="Année Scolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retards",
                        to="application.classe",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retards",
                        to="application.eleve",
                        verbose_name="Élève",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retards",
                        to="application.matiere",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "semestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retards",
                        to="application.semestre",
                        verbose_name="Semestre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retard",
                "verbose_name_plural": "Retards",
                "ordering": ["-date"],
            },
        ),
    ]
