# Generated by Django 5.1.3 on 2025-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0030_absence_retard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="justifiee",
            field=models.CharField(
                choices=[("Oui", "Oui"), ("Non", "Non")],
                default="Non",
                max_length=3,
                verbose_name="Absence justifiée",
            ),
        ),
    ]
