# Generated by Django 5.1.3 on 2025-02-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0031_alter_absence_justifiee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retard",
            name="justifie",
            field=models.CharField(
                choices=[("Oui", "Oui"), ("Non", "Non")],
                default="Non",
                max_length=3,
                verbose_name="Retard justifié",
            ),
        ),
    ]
