# Generated by Django 5.1.3 on 2025-02-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0034_surveillant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant payé"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("P", "Payé"), ("N", "Non payé"), ("R", "En retard")],
                        default="N",
                        max_length=1,
                        verbose_name="Statut du paiement",
                    ),
                ),
                (
                    "plan_paiement",
                    models.CharField(
                        choices=[
                            ("Mensuel", "Mensuel"),
                            ("Trimestriel", "Trimestriel"),
                            ("Semestriel", "Semestriel"),
                            ("Annuel", "Annuel"),
                        ],
                        max_length=20,
                        verbose_name="Plan de paiement",
                    ),
                ),
                (
                    "mois_annee",
                    models.CharField(
                        help_text="Format : MM/YYYY",
                        max_length=7,
                        verbose_name="Mois/Année concerné",
                    ),
                ),
                (
                    "commentaires",
                    models.TextField(
                        blank=True, null=True, verbose_name="Commentaires"
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="application.eleve",
                        verbose_name="Élève",
                    ),
                ),
            ],
        ),
    ]
