# Generated by Django 5.1.3 on 2025-02-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0035_paiement"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="reference",
            field=models.CharField(
                default=1,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Référence",
            ),
            preserve_default=False,
        ),
    ]
